---
layout: cv
title: Seth Laub
---
# Seth Laub
BYU-I Accounting, CPA Eligible 2027

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Full time student, Accounting Lab TA

### Specialized in

[Audit](https://rsmus.com/services/audit-services.html), GAAP, bookkeeping, VBA, Python, SQL


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education

BYU-I Bachelor of Accounting
Future ISU

## Experience
Chief Financial Officer  
Startup Company (Rexburg, Idaho)  
- Oversaw all financial operations, including budgeting and forecasting.  
- Implemented cost-saving measures that improved profitability.  
- Coordinated with external auditors and managed compliance.  
Jan 2023 - Apr 2023

Roofer  
Scott Myers and Sons Roofing (Boise, Idaho)  
- Ensured quality installation of roofs for both new and existing construction.  
- Estimated costs and prepared bids for over 20 new jobs.  
- Managed a team of 5 coworkers, ensuring each project was completed accurately.  
Summers 2021, 2022

Technician  
Green Way Pest Control (Phoenix, Arizona)  
- Treated dozens of homes daily with various pest control solutions.  
- Improved customer retention by 10% through relationship-building and service quality.  
Summer 2020

Full Time Volunteer  
The Church of Jesus Christ of Latter-Day Saints (Houston, Texas)  
- Organized leadership roles and training events.  
- Engaged in community outreach, fostering relationships across diverse communities.  
2018 - 2020
Audit Staff  
RSM (Denver, Colorado)




<!-- ### Footer

Last updated: May 2013 -->